package functions

import (
	"fmt"
	"io"
	"log"

	functionrpc "github.com/azure/azure-functions-golang-worker/proto"
)

// WorkerServer implements the FunctionRpcServer interface generated by protoc.
type WorkerServer struct {
	// Embed the unimplemented server to satisfy newer versions of the gRPC code generator.
	functionrpc.UnimplementedFunctionRpcServer

	dispatcher *Dispatcher
}

// NewWorkerServer constructs a new WorkerServer.
func NewWorkerServer(dispatcher *Dispatcher) *WorkerServer {
	return &WorkerServer{
		dispatcher: dispatcher,
	}
}

// func (s *WorkerServer) EventStream(stream functionrpc.FunctionRpc_EventStreamServer) error {
//     // Existing implementation ...
//     return nil
// }

// EventStream is the bidirectional streaming RPC method that the Host calls to communicate with the worker.
// It receives StreamingMessage from the Host and (optionally) sends StreamingMessage responses.
func (s *WorkerServer) EventStream(stream functionrpc.FunctionRpc_EventStreamServer) error {
	for {
		// 1. Wait for the next incoming StreamingMessage from the host.
		msg, err := stream.Recv()
		if err == io.EOF {
			// Host closed the stream. Return to end the connection.
			log.Println("EventStream closed by host.")
			return nil
		}
		if err != nil {
			// Some error occurred while receiving. You can handle or log it as needed.
			return fmt.Errorf("error receiving message from host: %w", err)
		}

		// 2. Dispatch the message based on its oneof content.
		//    The dispatcher should figure out the message type and call the appropriate handler.
		response, dispatchErr := s.dispatcher.Dispatch(msg)
		if dispatchErr != nil {
			// You might choose to log or handle the error, or even send back an error response.
			log.Printf("Error dispatching message: %v\n", dispatchErr)
			// We continue to the next message (or you could return an error here if it’s critical).
		}

		// 3. If the dispatcher returned a response, send it back to the host.
		if response != nil {
			sendErr := stream.Send(response)
			if sendErr != nil {
				// If we can’t send a response, we can choose to log and continue or return an error.
				log.Printf("Error sending response: %v\n", sendErr)
				// For now, just continue reading messages.
			}
		}
	}
}
