package internal

import (
	"fmt"
	"io"
	"log"
	"net"

	// Import your generated protobuf code (assuming the package is named "functionrpc").
	// Adjust the module path and package name to match how you've generated the .pb.go files.
	functionrpc "github.com/azure/azure-functions-golang-worker/proto"

	// gRPC imports
	"google.golang.org/grpc"
)

// WorkerServer implements the FunctionRpcServer interface generated by protoc.
type WorkerServer struct {
	// Embed the unimplemented server to satisfy newer versions of the gRPC code generator.
	functionrpc.UnimplementedFunctionRpcServer

	dispatcher *Dispatcher
}

// NewWorkerServer constructs a new WorkerServer.
func NewWorkerServer(dispatcher *Dispatcher) *WorkerServer {
	return &WorkerServer{
		dispatcher: dispatcher,
	}
}

// func (s *WorkerServer) EventStream(stream functionrpc.FunctionRpc_EventStreamServer) error {
//     // Existing implementation ...
//     return nil
// }

// EventStream is the bidirectional streaming RPC method that the Host calls to communicate with the worker.
// It receives StreamingMessage from the Host and (optionally) sends StreamingMessage responses.
func (s *WorkerServer) EventStream(stream functionrpc.FunctionRpc_EventStreamServer) error {
	for {
		// 1. Wait for the next incoming StreamingMessage from the host.
		msg, err := stream.Recv()
		if err == io.EOF {
			// Host closed the stream. Return to end the connection.
			log.Println("EventStream closed by host.")
			return nil
		}
		if err != nil {
			// Some error occurred while receiving. You can handle or log it as needed.
			return fmt.Errorf("error receiving message from host: %w", err)
		}

		// 2. Dispatch the message based on its oneof content.
		//    The dispatcher should figure out the message type and call the appropriate handler.
		response, dispatchErr := s.dispatcher.Dispatch(msg)
		if dispatchErr != nil {
			// You might choose to log or handle the error, or even send back an error response.
			log.Printf("Error dispatching message: %v\n", dispatchErr)
			// We continue to the next message (or you could return an error here if it’s critical).
		}

		// 3. If the dispatcher returned a response, send it back to the host.
		if response != nil {
			sendErr := stream.Send(response)
			if sendErr != nil {
				// If we can’t send a response, we can choose to log and continue or return an error.
				log.Printf("Error sending response: %v\n", sendErr)
				// For now, just continue reading messages.
			}
		}
	}
}

// StartWorkerServer is an optional helper function that creates and runs a gRPC server,
// registers the WorkerServer implementation, and blocks until the server shuts down.
func StartWorkerServer(addr string, dispatcher *Dispatcher) error {
	// 1. Create a new gRPC server.
	grpcServer := grpc.NewServer()

	// 2. Create the WorkerServer and register it with the generated FunctionRpc service.
	workerServer := NewWorkerServer(dispatcher)
	functionrpc.RegisterFunctionRpcServer(grpcServer, workerServer)

	// 3. Listen on the specified address.
	lis, err := net.Listen("tcp", addr)
	if err != nil {
		return fmt.Errorf("failed to listen on %s: %w", addr, err)
	}

	log.Printf("Go Worker is listening on %s\n", addr)

	// 4. Serve (blocking call) until an error occurs or the server is stopped.
	return grpcServer.Serve(lis)
}
